export const MILESTONE_PERSON_1 = "person-1-data-store-api-contracts" as const;

export const integrationManifestTask1 = {
  milestone: MILESTONE_PERSON_1,
  owner: "Person 1",
  status: "landed",
  docs: {
    sourcePlan: "middlewaredoc/PLAN.md#person-1---data-store-and-api-contracts",
    sourceSpec: "middlewaredoc/SPEC.md",
    handoff: "middlewaredoc/MILESTONE_PERSON_1.md",
  },
  serverFiles: [
    "apps/server/src/types.ts",
    "apps/server/src/store.ts",
    "apps/server/src/config.ts",
    "apps/server/src/app.ts",
    "apps/server/src/agent-service.ts",
    "apps/server/src/workspace.ts",
  ],
  webFiles: ["apps/web/src/types.ts", "apps/web/src/api.ts"],
  configKeys: [
    "MEMORY_ENABLED",
    "MEMORY_EXTRACTOR",
    "MEMORY_EXTRACT_TIMEOUT_MS",
    "REVIEW_ALL_SKILLS",
    "SKILLS_DIR",
  ],
  contracts: {
    groupMembership: "AgentGroup.members[{ agentId, role }] exactly three, one per role",
    soloFreshThread: "SendMessageInput.freshThread passes threadId null to the runner",
    agentLease: "AgentLease.acquireAgent/releaseAgent serializes solo and group work per Agent",
    runnerSharedCode: "RunnerRequest.sharedCodePath is optional and omitted for solo runs",
    memoryBlocks: "writeInstructions preserves <!-- memory:* --> managed blocks",
  },
  databaseArrays: [
    "groups",
    "groupTasks",
    "groupMessages",
    "groupParticipants",
    "groupPlanNodes",
    "contextInjections",
    "runtimeLocks",
    "notes",
    "landedMemoryFiles",
    "grants",
  ],
  routes: [
    "GET /api/groups",
    "POST /api/groups",
    "GET /api/groups/:id",
    "PATCH /api/groups/:id",
    "POST /api/groups/:id/tasks",
    "GET /api/groups/:id/tasks/:taskId",
    "POST /api/groups/:id/tasks/:taskId/cancel",
    "GET /api/groups/:id/tasks/:taskId/timeline",
    "GET /api/groups/:id/tasks/:taskId/context-injections",
    "GET /api/notes",
    "POST /api/notes/:id/review",
    "POST /api/notes/:id/revoke",
    "GET /api/agents/:id/memory",
    "GET /api/tasks/:id/grants",
  ],
  handoffs: {
    person2: [
      "Implement startGroupTask/cancelGroupTask behavior behind existing route stubs",
      "Call acquireAgent/releaseAgent for group nodes",
      "Pass RunnerRequest.sharedCodePath for group runs",
      "Import replaceManagedBlock/removeManagedBlock for group-task AGENTS.md sections",
    ],
    person3: [
      "Use listNotes/reviewNote/revokeNote/listAgentMemory/listTaskGrants route shapes",
      "Import replaceManagedBlock/removeManagedBlock from workspace.ts for landed memory",
      "Keep MEMORY_EXTRACTOR=ark as the application default; offline tests opt into fake explicitly",
    ],
    person4: [
      "Use apps/web/src/types.ts DTOs only",
      "Create/update groups with members, not memberAgentIds",
      "Use freshThread on solo messages to prove landed memory is reloaded",
    ],
  },
  verification: ["npm run check"],
} as const;
